version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: kanban_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: always
volumes:
  postgres_data:
